### ISSUE TITLE
asset cache entries generated in one release folder are not usable by another release (with sprockets 3.x)

### ISSUE THREAD

**Issue by bughit** [capistrano/rails#130] opened 2015-08-13 18:41 UTC
rails 4.2.3, ruby 2.2.2, sprockets 3.2.x

evidently the full asset path is used to produce the asset cache key

so if you run assets:precompile in release1 the generated cache is not usable in release2 even though shared

so how can you actually reuse the cache?

**Comment by bughit** [comment] 2015-08-13 19:29
looks like sprockets 3.3.0 addresses this by using relative paths

**Comment by bughit** [comment] 2015-08-13 20:43
but 3.3.0 has other problems (https://github.com/rails/sprockets/issues/96)

**Comment by bughit** [comment] 2015-08-13 23:47
sprockets 2.12.4 works

**Comment by baburdick** [comment] 2016-01-29 22:30
Any update to this?

**Comment by mattbrictson** [comment] 2016-01-29 23:29
I don't understand the issue. Can you elaborate?

By default the Sprockets cache is placed in `<rails root>/tmp/cache/assets`, so as long as you are symlinking `tmp/cache` in Capistrano you should be good.

**Comment by will-in-wi** [comment] 2016-08-06 12:11
This seems like a sprockets bug in an older version of sprockets. Sprockets 3.7 is out, and 4.0 is being worked on. Is this still an issue?

**Comment by will-in-wi** [comment] 2017-10-01 12:48
Given that this ticket hasn't had activity for a year, and the Sprockets landscape has changed quite a bit since then, I'm closing this ticket. If anyone can reproduce, feel free to reopen.

**Closed by will-in-wi** 2017-10-01 12:48 UTC
